"""
Seed data for the inventory management system
"""

CATEGORIES = [
    {"name": "Electronics", "description": "Electronic devices and accessories"},
    {"name": "Office Supplies", "description": "Stationery and office equipment"},
    {"name": "Furniture", "description": "Office and warehouse furniture"},
    {"name": "Packaging", "description": "Boxes, labels, and shipping materials"},
    {"name": "Tools", "description": "Maintenance and repair tools"},
]

WAREHOUSES = [
    {
        "name": "Main Warehouse",
        "location": "123 Industrial Blvd, Austin, TX 78704",
        "isDefault": True,
    },
    {
        "name": "West Coast Storage",
        "location": "456 Pacific Ave, Los Angeles, CA 90001",
        "isDefault": False,
    },
    {
        "name": "Regional Distribution",
        "location": "789 Commerce Parkway, Dallas, TX 75201",
        "isDefault": False,
    },
]

PRODUCTS = [
    {
        "name": "Wireless Mouse",
        "sku": "WM-001",
        "barcode": "1234567890123",
        "categoryId": 1,
        "price": 29.99,
        "cost": 15.00,
        "stock": 150,
        "reorderLevel": 20,
        "status": "Active",
        "description": "Ergonomic wireless mouse with USB receiver",
        "warehouseId": 1,
    },
    {
        "name": "USB-C Hub",
        "sku": "UH-002",
        "barcode": "1234567890124",
        "categoryId": 1,
        "price": 49.99,
        "cost": 28.00,
        "stock": 75,
        "reorderLevel": 15,
        "status": "Active",
        "description": "7-in-1 USB-C hub with HDMI and SD card reader",
        "warehouseId": 1,
    },
    {
        "name": "A4 Paper Ream",
        "sku": "AP-003",
        "barcode": "1234567890125",
        "categoryId": 2,
        "price": 8.99,
        "cost": 4.50,
        "stock": 300,
        "reorderLevel": 50,
        "status": "Active",
        "description": "500 sheets premium 80gsm A4 paper",
        "warehouseId": 1,
    },
    {
        "name": "Office Chair",
        "sku": "OC-004",
        "barcode": "1234567890126",
        "categoryId": 3,
        "price": 249.99,
        "cost": 140.00,
        "stock": 24,
        "reorderLevel": 5,
        "status": "Active",
        "description": "Adjustable ergonomic office chair with lumbar support",
        "warehouseId": 1,
    },
    {
        "name": "Shipping Box (Medium)",
        "sku": "SB-005",
        "barcode": "1234567890127",
        "categoryId": 4,
        "price": 2.49,
        "cost": 0.80,
        "stock": 1200,
        "reorderLevel": 200,
        "status": "Active",
        "description": "Medium corrugated cardboard shipping box 12x9x6",
        "warehouseId": 2,
    },
    {
        "name": "Mechanical Keyboard",
        "sku": "MK-006",
        "barcode": "1234567890128",
        "categoryId": 1,
        "price": 89.99,
        "cost": 52.00,
        "stock": 45,
        "reorderLevel": 10,
        "status": "Active",
        "description": "RGB mechanical keyboard with Cherry MX switches",
        "warehouseId": 1,
    },
    {
        "name": "Monitor Stand",
        "sku": "MS-007",
        "barcode": "1234567890129",
        "categoryId": 3,
        "price": 39.99,
        "cost": 18.00,
        "stock": 32,
        "reorderLevel": 8,
        "status": "Active",
        "description": "Adjustable monitor stand with storage drawer",
        "warehouseId": 1,
    },
    {
        "name": "Desk Lamp",
        "sku": "DL-008",
        "barcode": "1234567890130",
        "categoryId": 3,
        "price": 59.99,
        "cost": 28.00,
        "stock": 18,
        "reorderLevel": 5,
        "status": "Active",
        "description": "LED desk lamp with adjustable brightness and color temperature",
        "warehouseId": 1,
    },
    {
        "name": "Packing Tape",
        "sku": "PT-009",
        "barcode": "1234567890131",
        "categoryId": 4,
        "price": 3.99,
        "cost": 1.20,
        "stock": 500,
        "reorderLevel": 100,
        "status": "Active",
        "description": "Heavy-duty transparent packing tape 2-inch roll",
        "warehouseId": 2,
    },
    {
        "name": "Webcam HD",
        "sku": "WC-010",
        "barcode": "1234567890132",
        "categoryId": 1,
        "price": 69.99,
        "cost": 35.00,
        "stock": 28,
        "reorderLevel": 8,
        "status": "Active",
        "description": "1080p HD webcam with built-in microphone",
        "warehouseId": 1,
    },
]

SUPPLIERS = [
    {
        "name": "TechSupply Co.",
        "email": "orders@techsupply.com",
        "phone": "+1-555-0101",
        "address": "123 Tech Park, Austin, TX 78704",
        "contactPerson": "John Miller",
    },
    {
        "name": "Office Depot Wholesale",
        "email": "wholesale@officedepot.com",
        "phone": "+1-555-0102",
        "address": "456 Commerce Blvd, Dallas, TX 75201",
        "contactPerson": "Sarah Chen",
    },
    {
        "name": "FurniPro Ltd",
        "email": "sales@furnipro.com",
        "phone": "+1-555-0103",
        "address": "789 Industrial Way, Houston, TX 77001",
        "contactPerson": "Mike Roberts",
    },
    {
        "name": "PackagePro Solutions",
        "email": "sales@packagepro.com",
        "phone": "+1-555-0104",
        "address": "321 Logistics Ave, Los Angeles, CA 90001",
        "contactPerson": "Lisa Anderson",
    },
]

CUSTOMERS = [
    {
        "name": "Acme Corp",
        "email": "procurement@acme.com",
        "phone": "+1-555-0201",
        "address": "100 Business Ave, New York, NY 10001",
    },
    {
        "name": "StartupHub Inc",
        "email": "orders@startuphub.io",
        "phone": "+1-555-0202",
        "address": "200 Innovation Dr, San Francisco, CA 94102",
    },
    {
        "name": "Retail Plus",
        "email": "buying@retailplus.com",
        "phone": "+1-555-0203",
        "address": "300 Market St, Chicago, IL 60601",
    },
    {
        "name": "Global Enterprises",
        "email": "procurement@globalent.com",
        "phone": "+1-555-0204",
        "address": "400 Enterprise Blvd, Boston, MA 02101",
    },
    {
        "name": "SmallBiz Solutions",
        "email": "orders@smallbiz.com",
        "phone": "+1-555-0205",
        "address": "500 Commerce Park, Seattle, WA 98101",
    },
]

# Sample purchases, sales, and movements will be generated programmatically
