from fastapi import APIRouter
from app.api.endpoints import auth, seed, products, customers, suppliers, sales, purchases, quotes, categories, warehouses, users, dashboard, inventory
from app.api.endpoints import settings, notifications, roles, audit_logs, serial_numbers, batches, returns, invoices, uploads, shipments, reports

api_router = APIRouter()

api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(seed.router, prefix="/seed", tags=["seed"])
api_router.include_router(categories.router, prefix="/categories", tags=["categories"])
api_router.include_router(warehouses.router, prefix="/warehouses", tags=["warehouses"])
api_router.include_router(users.router, prefix="/users", tags=["users"])
api_router.include_router(dashboard.router, prefix="/dashboard", tags=["dashboard"])
api_router.include_router(inventory.router, prefix="/inventory", tags=["inventory"])
api_router.include_router(products.router, prefix="/products", tags=["products"])
api_router.include_router(customers.router, prefix="/customers", tags=["customers"])
api_router.include_router(suppliers.router, prefix="/suppliers", tags=["suppliers"])
api_router.include_router(sales.router, prefix="/sales", tags=["sales"])
api_router.include_router(purchases.router, prefix="/purchases", tags=["purchases"])
api_router.include_router(quotes.router, prefix="/quotes", tags=["quotes"])
api_router.include_router(settings.router, prefix="/settings", tags=["settings"])
api_router.include_router(notifications.router, prefix="/notifications", tags=["notifications"])
api_router.include_router(roles.router, prefix="/roles", tags=["roles"])
api_router.include_router(audit_logs.router, prefix="/audit-logs", tags=["audit-logs"])
api_router.include_router(serial_numbers.router, prefix="/serial-numbers", tags=["serial-numbers"])
api_router.include_router(batches.router, prefix="/batches", tags=["batches"])
api_router.include_router(returns.router, prefix="/returns", tags=["returns"])
api_router.include_router(invoices.router, prefix="/invoices", tags=["invoices"])
api_router.include_router(uploads.router, prefix="/uploads", tags=["uploads"])
api_router.include_router(shipments.router, prefix="/shipments", tags=["shipments"])
api_router.include_router(reports.router, prefix="/reports", tags=["reports"])
